#!/usr/bin/env bash
set -euo pipefail

MODEL="${KILO_MODEL:-kilo/kilo-auto/free}"
CTX_DIR="kilo-context"
STATE_DIR=".git/kilo-sync"
IGNORE_FILE=".kilocodeignore"
IGNORE_BACKUP="${STATE_DIR}/kilocodeignore.backup"
IGNORE_STATE="${STATE_DIR}/kilocodeignore.state"

log() {
    printf '[sync-upstream] %s\n' "$*"
}

has_active_rebase() {
    [ -d .git/rebase-merge ] || [ -d .git/rebase-apply ]
}

cleanup_context() {
    if [ -f "$IGNORE_STATE" ]; then
        case "$(cat "$IGNORE_STATE")" in
            present)
                [ -f "$IGNORE_BACKUP" ] && cp "$IGNORE_BACKUP" "$IGNORE_FILE"
                ;;
            absent)
                rm -f "$IGNORE_FILE"
                ;;
        esac
        rm -f "$IGNORE_BACKUP" "$IGNORE_STATE"
    fi
    rm -rf "$CTX_DIR"
}

verify_clean() {
    cleanup_context
    if has_active_rebase; then
        log "Rebase is still active."
        git status --short
        return 1
    fi
    if git ls-files -u | grep -q .; then
        log "Unmerged paths remain."
        git ls-files -u
        return 1
    fi
    if ! git diff --quiet || ! git diff --cached --quiet; then
        log "Tracked changes remain."
        git status --short
        return 1
    fi
    if [ -f REBASE_NOTES.md ]; then
        log "REBASE_NOTES.md exists; human review is required."
        return 1
    fi
}

allow_path() {
    local path="$1"
    local dir=""
    local part
    local -a parts

    IFS='/' read -r -a parts <<< "$path"
    for ((i = 0; i < ${#parts[@]} - 1; i++)); do
        part="${parts[$i]}"
        if [ -z "$dir" ]; then
            dir="$part"
        else
            dir="${dir}/${part}"
        fi
        printf '!%s/\n' "$dir"
    done
    if [ "${#parts[@]}" -gt 1 ]; then
        printf '!%s/**\n' "$dir"
    fi
    printf '!%s\n' "$path"
}

prepare_kilo_context() {
    mkdir -p "$STATE_DIR" "$CTX_DIR"
    if [ ! -f "$IGNORE_STATE" ]; then
        if [ -f "$IGNORE_FILE" ]; then
            cp "$IGNORE_FILE" "$IGNORE_BACKUP"
            printf 'present\n' > "$IGNORE_STATE"
        else
            printf 'absent\n' > "$IGNORE_STATE"
        fi
    fi

    {
        printf '# Generated by sync-upstream-kilo.sh. Removed before push.\n'
        printf '*\n'
        printf '!.gitignore\n'
        printf '!REBASE_NOTES.md\n'
        printf '!%s/\n' "$CTX_DIR"
        printf '!%s/**\n' "$CTX_DIR"
        for path in "$@"; do
            [ -n "$path" ] || continue
            allow_path "$path"
        done
    } > "$IGNORE_FILE"
}

run_kilo() {
    local log_file="$1"
    local prompt_file="$2"

    set +e
    kilo run --auto --model "$MODEL" "$(cat "$prompt_file")" 2>&1 | tee "$log_file"
    local status=${PIPESTATUS[0]}
    set -e

    if grep -Eiq 'provider_unavailable|Provider returned error' "$log_file"; then
        log "Kilo provider failure detected."
        return 75
    fi
    if grep -Eiq 'Input length .*exceeds|maximum allowed input length|context.*too large|token.*limit' "$log_file"; then
        log "Kilo token-limit failure detected."
        return 76
    fi
    return "$status"
}

run_kilo_with_retry() {
    local log_file="$1"
    local prompt_file="$2"
    local max_attempts="${KILO_MAX_ATTEMPTS:-3}"
    local max_delay="${KILO_MAX_BACKOFF:-60}"
    local status=0
    local delay=5
    local attempt

    if ! [[ "$max_attempts" =~ ^[1-9][0-9]*$ ]]; then
        log "Invalid KILO_MAX_ATTEMPTS=${max_attempts}; expected positive integer."
        return 2
    fi

    for ((attempt = 1; attempt <= max_attempts; attempt++)); do
        status=0
        run_kilo "$log_file" "$prompt_file" || status=$?

        if [ "$status" -eq 75 ] && [ "$attempt" -lt "$max_attempts" ]; then
            log "Kilo provider failure on attempt ${attempt}/${max_attempts}; retrying in ${delay}s."
            sleep "$delay"
            delay=$((delay * 3))
            [ "$delay" -gt "$max_delay" ] && delay="$max_delay"
            continue
        fi
        return "$status"
    done
    return "$status"
}

write_conflict_prompt() {
    local file="$1"
    local prompt_file="$CTX_DIR/prompt.txt"

    cat > "$prompt_file" <<EOF
Resolve the git conflict in exactly this file:
$file

Rules:
- Edit only $file.
- Preserve fork-specific behavior unless upstream already has equivalent behavior.
- Prefer upstream APIs, names, and structure.
- Remove all conflict markers.
- Do not run git add, git commit, git rebase, or build commands.
- If the conflict is ambiguous, write REBASE_NOTES.md and exit non-zero.
EOF
}

resolve_conflicts() {
    local max_iters="${MAX_REBASE_ITERS:-20}"
    local conflicts file log_file prompt_file

    for ((iter = 1; iter <= max_iters; iter++)); do
        if ! has_active_rebase; then
            verify_clean
            return 0
        fi

        mapfile -t conflicts < <(git diff --name-only --diff-filter=U)
        if [ "${#conflicts[@]}" -eq 0 ]; then
            log "No unmerged paths; continuing rebase."
            GIT_EDITOR=: git rebase --continue
            continue
        fi

        for file in "${conflicts[@]}"; do
            log "Resolving conflict in ${file}"
            cleanup_context
            prepare_kilo_context "$file"
            write_conflict_prompt "$file"
            prompt_file="$CTX_DIR/prompt.txt"
            log_file="$CTX_DIR/kilo-conflict.log"

            local kilo_status=0
            run_kilo_with_retry "$log_file" "$prompt_file" || kilo_status=$?
            if [ "$kilo_status" -ne 0 ]; then
                log "Kilo failed while resolving ${file} (status ${kilo_status})."
                exit "$kilo_status"
            fi
            if [ -f REBASE_NOTES.md ]; then
                log "REBASE_NOTES.md exists; human review is required."
                exit 1
            fi
            if grep -nE '^(<<<<<<<|=======|>>>>>>>)' "$file"; then
                log "Conflict markers remain in ${file}."
                exit 1
            fi
            git add "$file"
        done

        if git ls-files -u | grep -q .; then
            log "Unmerged paths remain after staging."
            git ls-files -u
            exit 1
        fi
        cleanup_context
        GIT_EDITOR=: git rebase --continue
    done

    log "Rebase still active after ${max_iters} iterations."
    exit 1
}

extract_first_error() {
    local log_path="${1:-build.log}"
    local out_file="$CTX_DIR/first-error.txt"
    local pattern='(^|[ :])(fatal error|error:|undefined reference|collect2: error|ld returned|CMake Error)'
    local first_line start end
    mkdir -p "$CTX_DIR"

    if [ ! -s "$log_path" ]; then
        printf 'Build log %s is missing or empty.\n' "$log_path" > "$out_file"
        return
    fi

    first_line="$(grep -En "$pattern" "$log_path" | head -n 1 | cut -d: -f1 || true)"
    if [ -n "$first_line" ]; then
        start=$((first_line > 8 ? first_line - 8 : 1))
        end=$((first_line + 60))
        sed -n "${start},${end}p" "$log_path" > "$out_file"
    else
        tail -n 80 "$log_path" > "$out_file"
    fi
}

select_failure_log() {
    if [ -s configure.log ] && grep -Eq 'CMake Error|Configuring incomplete|-- Configuring incomplete' configure.log; then
        printf 'configure.log\n'
    elif [ -s build.log ]; then
        printf 'build.log\n'
    else
        printf 'configure.log\n'
    fi
}

infer_error_files() {
    local out_file="$CTX_DIR/files.txt"
    : > "$out_file"

    grep -Eo '([A-Za-z0-9_./+-]+\.(c|cc|cpp|cxx|h|hh|hpp|cuh|cu|m|mm))(:[0-9]+)?' "$CTX_DIR/first-error.txt" \
        | sed 's/:.*//' \
        | while read -r path; do
            [ -f "$path" ] && printf '%s\n' "$path"
        done | sort -u | head -n 1 > "$out_file" || true
}

write_build_prompt() {
    local prompt_file="$CTX_DIR/prompt.txt"
    local files
    files="$(tr '\n' ' ' < "$CTX_DIR/files.txt")"

    cat > "$prompt_file" <<EOF
Fix the first build error only.

Read:
- $CTX_DIR/first-error.txt

Allowed source files:
$files

Rules:
- Edit only the allowed source files.
- Preserve fork-specific behavior.
- Adapt to upstream APIs and names.
- Do not run git add, git commit, git rebase, or build commands.
- Do not inspect unrelated repository files.
- If the allowed files are insufficient, write REBASE_NOTES.md and exit non-zero.
EOF
}

build_once() {
    cmake -B build -DGGML_NATIVE=OFF -DGGML_BACKEND_DL=OFF -DLLAMA_CURL=OFF 2>&1 | tee configure.log &&
    cmake --build build -j"$(nproc)" 2>&1 | tee build.log
}

fix_build() {
    local max_attempts="${MAX_BUILD_FIX_ITERS:-3}"
    local status log_file prompt_file
    local -a files

    for ((attempt = 1; attempt <= max_attempts; attempt++)); do
        log "Build-fix attempt ${attempt}/${max_attempts}"
        cleanup_context
        extract_first_error "$(select_failure_log)"
        infer_error_files
        mapfile -t files < "$CTX_DIR/files.txt"
        if [ "${#files[@]}" -eq 0 ]; then
            log "Could not infer relevant files from build.log."
            exit 1
        fi

        prepare_kilo_context "${files[@]}"
        write_build_prompt
        prompt_file="$CTX_DIR/prompt.txt"
        log_file="$CTX_DIR/kilo-build-fix.log"

        status=0
        run_kilo_with_retry "$log_file" "$prompt_file" || status=$?

        if [ "$status" -ne 0 ]; then
            log "Kilo exited with status ${status}."
            exit "$status"
        fi

        cleanup_context
        if build_once; then
            if [ -f REBASE_NOTES.md ]; then
                log "REBASE_NOTES.md exists; human review is required."
                exit 1
            fi
            if has_active_rebase; then
                log "Build passed but rebase is still active."
                git status --short
                exit 1
            fi
            if ! git diff --quiet || ! git diff --cached --quiet; then
                git add -- "${files[@]}"
                git commit --amend --no-edit
            fi
            verify_clean
            return 0
        fi
    done

    log "Build still fails after ${max_attempts} attempts."
    exit 1
}

usage() {
    cat <<EOF
usage: $0 resolve-conflicts|fix-build|verify-clean|cleanup-context
EOF
}

trap 'cleanup_context || true' EXIT

case "${1:-}" in
    resolve-conflicts)
        resolve_conflicts
        ;;
    fix-build)
        fix_build
        ;;
    verify-clean)
        verify_clean
        ;;
    cleanup-context)
        cleanup_context
        ;;
    *)
        usage
        exit 2
        ;;
esac
